### ISSUE TITLE
error c3668

### ISSUE THREAD

**Issue by thunderdoksa** [SINTEF-9012/UnrealMosquitto#3]
I try compile, but receive this error message:

C:\testes\UnrealMosquitto\uemqtt_packeged\HostProject\Plugins\UEmqtt\Source\UEmqtt\Public/UnrealMosquittoRouter.h(37): error C3668: 'UUnrealMosquittoRouter::GetPinNameGivenIndex': method with override specifier 'override' did not override any base class methods
  C:\testes\UnrealMosquitto\uemqtt_packeged\HostProject\Plugins\UEmqtt\Source\UEmqtt\Public\UnrealMosquittoRouter.h(37): error C3668: 'UUnrealMosquittoRouter::GetPinNameGivenIndex': method with override specifier 'override' did not override any base class methods
  C:\testes\UnrealMosquitto\uemqtt_packeged\HostProject\Plugins\UEmqtt\Source\UEmqtt\Private\UnrealMosquittoRouter.cpp(162): error C2664: 'int32 TArray<FString,FDefaultAllocator>::Remove(const FString &)': cannot convert argument n from 'FName' to 'const FString &'
  C:\testes\UnrealMosquitto\uemqtt_packeged\HostProject\Plugins\UEmqtt\Source\UEmqtt\Public\UnrealMosquittoRouter.cpp(4): error C2084: function 'FString UUnrealMosquittoRouter::GetPinNameGivenIndex(int32)' already has a body

I already tried both the normal compilation as the routine as plugin, and it gives the same error.

**Comment by desotroyah** [comment]
Hi!
Are you using Unreal Engine 4.19? The API seems to have changed. The methods in question changed to const, therefore they are not recognized as being overridden...
Anyway, please try my fork: https://github.com/desotroyah/UnrealMosquitto
It was implemented for 4.19 and contains precompiled binaries so you should be able to use it without compiling at all.
Please report back if this fixes the issue.

**Comment by thunderdoksa** [comment]
Hi!!
your fork worked. Thank you!!!

**Comment by amar0k** [comment]
Hi @desotroyah what happened to your fork?

**Comment by AndyPants550** [comment]
@desotroyah  your fork seems to have disappeared.....please please bring it back

**Comment by amar0k** [comment]
Hey mate , I made my own and got it working as a plugin. I will.make a fork
tonight.

**Comment by AndyPants550** [comment]
Dude, You'll be my hero!

**Comment by amar0k** [comment]
Hey buddy ,

Try this https://github.com/ASimpson87/UnrealMosquitto4.21

Add it as a plugin through the editor. This was built in UE4.21.2 Let me know if you have any dramas just comment on that repo.

Cheers.

**Comment by AndyPants550** [comment]
@ASimpson87 HI, thanks for the plugin build.  It works a charm!

Problem is I can't seem to use it for a packaged build....as soon as I package i get fatal errors.

Any help would be appreciated

**Comment by alegroSandermann** [comment]
Please update to UE4.22/23
